### ISSUE TITLE
WOW!!!!

### ISSUE THREAD

**Issue by sarseniy** [KozyrevIN/infa_2021_kozyrev#3]
Я фанат вашей игровой студии! Мне знатно начихали в лицо. Когда продолжение? Всё круто, задание принято.

**Comment by KozyrevIN** [comment]
![coronavirus](https://user-images.githubusercontent.com/91452690/138664661-6385fa84-12a7-4bfa-8937-26e2d6b115b2.png)
Спасибо за распространение заражения
